package com.socialapp.services.util;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.socialapp.services.dao.Interest;


public class SocialappServiceUtils {
	
	public static List<Interest> getAllInterests() {
		List<Interest> list = new ArrayList<Interest>();
		list.add(new Interest(0, "Alle"));
		list.add(new Interest(475, "Abnehmen"));
		list.add(new Interest(376, "Aerobic"));
		list.add(new Interest(419, "Afrika"));
		list.add(new Interest(105, "Aktionen in der Gruppe"));
		list.add(new Interest(42, "Aktionen mit Hund"));
		list.add(new Interest(43, "Aktionen mit Kindern"));
		list.add(new Interest(44, "Aktionen tags�ber"));
		list.add(new Interest(525, "Alleinerziehend"));
		list.add(new Interest(45, "Alpinwandern"));
		list.add(new Interest(14, "Angeln"));
		list.add(new Interest(153, "Architektur"));
		list.add(new Interest(414, "Asien"));
		list.add(new Interest(161, "Astrologie"));
		list.add(new Interest(333, "Ausgehen"));
		list.add(new Interest(499, "Ausgehpartner"));
		list.add(new Interest(46, "Ausstellungen"));
		list.add(new Interest(491, "Australien"));
		list.add(new Interest(365, "Autos"));
		list.add(new Interest(492, "Backen"));
		list.add(new Interest(511, "Badesee / Baggersee"));
		list.add(new Interest(375, "Badeurlaub"));
		list.add(new Interest(17, "Badminton"));
		list.add(new Interest(374, "Ballett"));
		list.add(new Interest(466, "Ballonfahrt"));
		list.add(new Interest(156, "Basketball"));
		list.add(new Interest(413, "Basteln"));
		list.add(new Interest(494, "Bauchtanz"));
		list.add(new Interest(47, "Bergh�tten"));
		list.add(new Interest(151, "Bergsteigen"));
		list.add(new Interest(352, "Bergwandern"));
		list.add(new Interest(518, "Besenwirtschaft"));
		list.add(new Interest(424, "Bi Sexuell"));
		list.add(new Interest(97, "Biergarten"));
		list.add(new Interest(373, "Bildhauen"));
		list.add(new Interest(48, "Billiard"));
		list.add(new Interest(22, "Bogenschie�en"));
		list.add(new Interest(339, "Boule"));
		list.add(new Interest(49, "Bowling"));
		list.add(new Interest(562, "Brieffreundschaft (NEU)"));
		list.add(new Interest(510, "Brunchen"));
		list.add(new Interest(128, "Buddhismus"));
		list.add(new Interest(552, "Bulgarien (NEU)"));
		list.add(new Interest(50, "Cabrio Tour"));
		list.add(new Interest(35, "Camping"));
		list.add(new Interest(425, "Candlelightdinner"));
		list.add(new Interest(20, "Canyoning"));
		list.add(new Interest(362, "Chillen"));
		list.add(new Interest(235, "Coaching"));
		list.add(new Interest(51, "Comedy"));
		list.add(new Interest(94, "Computer"));
		list.add(new Interest(388, "Coworking"));
		list.add(new Interest(19, "Dart"));
		list.add(new Interest(351, "Dating"));
		list.add(new Interest(344, "Doppelkopf spielen"));
		list.add(new Interest(102, "Einkaufen - Shoppen"));
		list.add(new Interest(372, "Eishockey"));
		list.add(new Interest(93, "Eisstockschie�en"));
		list.add(new Interest(147, "Ern�hrung"));
		list.add(new Interest(96, "Erotisches"));
		list.add(new Interest(107, "Esoterisches allgemein"));
		list.add(new Interest(34, "Essen gehen"));
		list.add(new Interest(427, "Fackelwanderung"));
		list.add(new Interest(2, "Fahrradfahren"));
		list.add(new Interest(26, "Fallschirmspringen"));
		list.add(new Interest(174, "Fernwanderungen"));
		list.add(new Interest(411, "Festival"));
		list.add(new Interest(350, "Filme Abend"));
		list.add(new Interest(52, "Fitness"));
		list.add(new Interest(512, "Fitnessstudio"));
		list.add(new Interest(116, "FKK"));
		list.add(new Interest(561, "Flirten (NEU)"));
		list.add(new Interest(426, "Fondueabend"));
		list.add(new Interest(28, "Fotografieren"));
		list.add(new Interest(409, "Frankreich"));
		list.add(new Interest(53, "Freizeitparks"));
		list.add(new Interest(356, "Freizeitpartner"));
		list.add(new Interest(112, "Fremdsprache lernen"));
		list.add(new Interest(514, "Freunde finden / treffen"));
		list.add(new Interest(81, "Fr�hst�ckstreff"));
		list.add(new Interest(101, "Fussball"));
		list.add(new Interest(457, "Gardasee"));
		list.add(new Interest(520, "Garten Sharing"));
		list.add(new Interest(113, "Garten"));
		list.add(new Interest(149, "Ged�chtnistraining"));
		list.add(new Interest(524, "Geldanlage (NEU)"));
		list.add(new Interest(172, "Geocaching"));
		list.add(new Interest(80, "Geschichte"));
		list.add(new Interest(132, "Gesundheit"));
		list.add(new Interest(8, "Gleitschirmfliegen"));
		list.add(new Interest(54, "Golfen"));
		list.add(new Interest(106, "Grillen"));
		list.add(new Interest(384, "Gruppenreisen"));
		list.add(new Interest(383, "Handball"));
		list.add(new Interest(459, "Handwerken"));
		list.add(new Interest(257, "Heilkr�uter"));
		list.add(new Interest(405, "Hunde"));
		list.add(new Interest(150, "H�ttenwanderung"));
		list.add(new Interest(55, "Inlineskaten"));
		list.add(new Interest(416, "Irland"));
		list.add(new Interest(526, "Islam (NEU)"));
		list.add(new Interest(395, "Italien"));
		list.add(new Interest(124, "Jagd"));
		list.add(new Interest(23, "Jogging"));
		list.add(new Interest(56, "Kabarett"));
		list.add(new Interest(162, "Kampfsport"));
		list.add(new Interest(57, "Kanutour"));
		list.add(new Interest(330, "Kanuwandern"));
		list.add(new Interest(91, "Karaoke"));
		list.add(new Interest(92, "Karten spielen"));
		list.add(new Interest(140, "Kartenlegen"));
		list.add(new Interest(406, "Katzen"));
		list.add(new Interest(58, "Kegeln"));
		list.add(new Interest(15, "Kino"));
		list.add(new Interest(100, "Kitesurfen"));
		list.add(new Interest(33, "Klettern"));
		list.add(new Interest(334, "Klettersteige"));
		list.add(new Interest(30, "Kochen"));
		list.add(new Interest(179, "Kochkurse"));
		list.add(new Interest(469, "Kochpartner"));
		list.add(new Interest(484, "Kochparty"));
		list.add(new Interest(59, "Konzerte"));
		list.add(new Interest(560, "Kr�uterwanderung (NEU)"));
		list.add(new Interest(38, "Kultur"));
		list.add(new Interest(39, "Kunst"));
		list.add(new Interest(60, "Kunstgeschichte"));
		list.add(new Interest(61, "Kunsthandwerken"));
		list.add(new Interest(10, "Kurzreisen"));
		list.add(new Interest(382, "Kuscheln"));
		list.add(new Interest(429, "Kuschelparty"));
		list.add(new Interest(423, "Lesbisch (NEU)"));
		list.add(new Interest(114, "Lesen"));
		list.add(new Interest(412, "M�delsabend"));
		list.add(new Interest(63, "Malen"));
		list.add(new Interest(415, "M�nnerabend"));
		list.add(new Interest(64, "Marathonlaufen"));
		list.add(new Interest(421, "Maskenball"));
		list.add(new Interest(276, "Massagen"));
		list.add(new Interest(89, "Meditation"));
		list.add(new Interest(120, "Mentaltraining"));
		list.add(new Interest(65, "Messebesuche"));
		list.add(new Interest(148, "Minigolf"));
		list.add(new Interest(363, "Mode"));
		list.add(new Interest(175, "Modellbau"));
		list.add(new Interest(465, "Moto Cross"));
		list.add(new Interest(98, "Motorboot"));
		list.add(new Interest(31, "Motorradfahren"));
		list.add(new Interest(460, "Motorradtouren"));
		list.add(new Interest(66, "Motorsport"));
		list.add(new Interest(332, "Mountainbiken"));
		list.add(new Interest(16, "Musicals"));
		list.add(new Interest(143, "Musik - Allgemein"));
		list.add(new Interest(67, "Musik - Alternative"));
		list.add(new Interest(346, "Musik - Blues"));
		list.add(new Interest(99, "Musik - House"));
		list.add(new Interest(68, "Musik - Jazz"));
		list.add(new Interest(115, "Musik - Klassik"));
		list.add(new Interest(62, "Musik - Live"));
		list.add(new Interest(69, "Musik - Metal"));
		list.add(new Interest(345, "Musik - Oldies"));
		list.add(new Interest(70, "Musik - Rock"));
		list.add(new Interest(347, "Musik - Schlager"));
		list.add(new Interest(71, "Musik - Soul"));
		list.add(new Interest(103, "Musizieren"));
		list.add(new Interest(274, "Mystik"));
		list.add(new Interest(25, "Natur"));
		list.add(new Interest(523, "Nebenjob (Suche)"));
		list.add(new Interest(329, "Neue Leute kennenlernen"));
		list.add(new Interest(129, "Nordic Skating - SKIKE"));
		list.add(new Interest(6, "Nordic Walking"));
		list.add(new Interest(342, "Oldtimer"));
		list.add(new Interest(72, "Oper"));
		list.add(new Interest(470, "Paintball / Gotcha"));
		list.add(new Interest(400, "Partnersuche"));
		list.add(new Interest(7, "Partys"));
		list.add(new Interest(402, "PC Spiele"));
		list.add(new Interest(118, "Pers�nlichkeitsentwicklung"));
		list.add(new Interest(404, "Pferde"));
		list.add(new Interest(331, "Pflanzen"));
		list.add(new Interest(397, "Philosophie"));
		list.add(new Interest(108, "Picknick"));
		list.add(new Interest(529, "Pilates"));
		list.add(new Interest(158, "Pilgern"));
		list.add(new Interest(340, "Pilze suchen"));
		list.add(new Interest(534, "Pokern"));
		list.add(new Interest(509, "Polen"));
		list.add(new Interest(117, "Politik"));
		list.add(new Interest(527, "Polygam leben (NEU)"));
		list.add(new Interest(500, "Pr� Astronautik (NEU)"));
		list.add(new Interest(432, "Programmieren - PHP"));
		list.add(new Interest(119, "Psychologie"));
		list.add(new Interest(183, "Qi Gong"));
		list.add(new Interest(167, "Radwandern"));
		list.add(new Interest(73, "Reisen - Last minute"));
		list.add(new Interest(336, "Reisen mit Rucksack"));
		list.add(new Interest(4, "Reisen"));
		list.add(new Interest(355, "Reisepartner"));
		list.add(new Interest(403, "Reitbeteiligungen"));
		list.add(new Interest(36, "Reiten"));
		list.add(new Interest(135, "Reptilien"));
		list.add(new Interest(130, "Rum�nien"));
		list.add(new Interest(506, "Russland"));
		list.add(new Interest(5, "Sauna"));
		list.add(new Interest(341, "Schach"));
		list.add(new Interest(74, "Schlittschuhlaufen"));
		list.add(new Interest(75, "Schneeschuhlaufen"));
		list.add(new Interest(123, "Schreiben"));
		list.add(new Interest(41, "Schwimmen"));
		list.add(new Interest(422, "Schwul (NEU)"));
		list.add(new Interest(464, "Science Fiction"));
		list.add(new Interest(298, "Seelenpartner"));
		list.add(new Interest(157, "Segelfliegen"));
		list.add(new Interest(417, "Segeln - Mitsegeln"));
		list.add(new Interest(12, "Segeln"));
		list.add(new Interest(303, "Singen"));
		list.add(new Interest(178, "Single Kind Events"));
		list.add(new Interest(176, "Singlereisen"));
		list.add(new Interest(496, "Singles mit Behinderung"));
		list.add(new Interest(177, "Singletreffen"));
		list.add(new Interest(343, "Skat spielen"));
		list.add(new Interest(462, "Skateboard (NEU)"));
		list.add(new Interest(32, "Skifahren"));
		list.add(new Interest(76, "Skilanglauf"));
		list.add(new Interest(463, "Slackline"));
		list.add(new Interest(533, "Smart fahren (NEU)"));
		list.add(new Interest(109, "Snowboarden"));
		list.add(new Interest(408, "Spanien"));
		list.add(new Interest(29, "Spazieren gehen"));
		list.add(new Interest(553, "Speeddating (NEU)"));
		list.add(new Interest(554, "Speedminton (NEU)"));
		list.add(new Interest(27, "Spieleabend"));
		list.add(new Interest(493, "Spielen - Backgammon (NEU)"));
		list.add(new Interest(348, "Spieleparty"));
		list.add(new Interest(90, "Spirituelles"));
		list.add(new Interest(77, "Spontanaktionen"));
		list.add(new Interest(37, "Sport"));
		list.add(new Interest(164, "Sportklettern"));
		list.add(new Interest(407, "Sportpartner"));
		list.add(new Interest(461, "Sportpartnerin"));
		list.add(new Interest(192, "Sporttauchen"));
		list.add(new Interest(78, "Squash"));
		list.add(new Interest(337, "St�dtereisen"));
		list.add(new Interest(79, "Stammtisch"));
		list.add(new Interest(483, "Sylvesterparty"));
		list.add(new Interest(160, "Tai Chi"));
		list.add(new Interest(187, "Tantra"));
		list.add(new Interest(430, "Tanzen - Bachata"));
		list.add(new Interest(431, "Tanzen - Discofox"));
		list.add(new Interest(387, "Tanzen - Salsa"));
		list.add(new Interest(398, "Tanzen - Tango"));
		list.add(new Interest(433, "Tanzen - Turniertanz"));
		list.add(new Interest(399, "Tanzen - Zumba"));
		list.add(new Interest(18, "Tanzen gehen"));
		list.add(new Interest(474, "Tanzkurs"));
		list.add(new Interest(390, "Tanzpartner"));
		list.add(new Interest(531, "Tattoos"));
		list.add(new Interest(95, "Tauchen / Schnorcheln"));
		list.add(new Interest(391, "Tauchpartner"));
		list.add(new Interest(82, "Technik"));
		list.add(new Interest(21, "Tennis"));
		list.add(new Interest(519, "Tennispartner"));
		list.add(new Interest(121, "The Work nach Byron Katie"));
		list.add(new Interest(40, "Theater"));
		list.add(new Interest(134, "Tiere"));
		list.add(new Interest(110, "Tischtennis"));
		list.add(new Interest(482, "T�pfern"));
		list.add(new Interest(166, "Trekking"));
		list.add(new Interest(490, "Triathlon"));
		list.add(new Interest(354, "Tr�del und Flohm�rkte"));
		list.add(new Interest(508, "T�rkei"));
		list.add(new Interest(401, "�berwintern im Ausland"));
		list.add(new Interest(513, "Vereine"));
		list.add(new Interest(83, "Videografieren"));
		list.add(new Interest(104, "Volksfest"));
		list.add(new Interest(84, "Volleyball (Beach)"));
		list.add(new Interest(9, "Walking"));
		list.add(new Interest(327, "Wandern f�r Anf�nger"));
		list.add(new Interest(185, "Wandern f�r Singles"));
		list.add(new Interest(184, "Wandern mit Hund"));
		list.add(new Interest(328, "Wandern mit Kindern"));
		list.add(new Interest(1, "Wandern"));
		list.add(new Interest(389, "Wanderpartner"));
		list.add(new Interest(165, "Wanderreiten"));
		list.add(new Interest(85, "Wasserski"));
		list.add(new Interest(530, "Weihnachtsmarkt"));
		list.add(new Interest(13, "Weinproben"));
		list.add(new Interest(24, "Wellness"));
		list.add(new Interest(335, "Weltreisen"));
		list.add(new Interest(88, "Windsurfen"));
		list.add(new Interest(86, "Wissenschaft"));
		list.add(new Interest(11, "Wochenendtrip"));
		list.add(new Interest(126, "Wohnmobil - Gruppenreise"));
		list.add(new Interest(127, "Wohnmobil - Ich habe eins"));
		list.add(new Interest(87, "Wohnmobil Tour"));
		list.add(new Interest(381, "Wohnmobilreisen"));
		list.add(new Interest(386, "Wohnwagen- ich habe einen"));
		list.add(new Interest(385, "Wohnwagen"));
		list.add(new Interest(3, "Yoga"));
		list.add(new Interest(144, "Zauberei"));
		list.add(new Interest(521, "Zeichnen"));
		list.add(new Interest(495, "Zelten"));
		return list;
	}

	public static Map<String, Integer> getInterestNameToIdMap() {
		Map<String, Integer> map = new HashMap<String, Integer>();
		List<Interest> interests = getAllInterests();
		for (Interest interest : interests) {
			map.put(interest.getInterestName(), interest.getId());
		}
		return map;
	}

	public static String md5(String plaintext) {
		byte[] digest = null;
		try {
			MessageDigest m = MessageDigest.getInstance("MD5");
			m.reset();
			m.update(plaintext.getBytes());
			digest = m.digest();
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}

		BigInteger bigInt = new BigInteger(1, digest);
		String md5 = bigInt.toString(16);
		if (md5.length() == 31) {
			md5 = '0' + md5;
		}
		return md5;
	}

}
